language: java
dist: xenial

jdk:
  - openjdk8
  - openjdk11
  
install: true

script: mvn clean install -Dgpg.skip -Dmaven.javadoc.skip=true -P generate-client-api -B -V

cache:
  directories:
  - $HOME/.m2

env:
  global:
    - CODECOV_TOKEN=d0840173-78bd-4ca6-b97c-4cf1705db312

after_success:
  - bash <(curl -s https://codecov.io/bash)